---
- name: Install ClamAV
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ clamav_packages }}"

- name: Enable daily fresh clam signature updates
  ansible.builtin.systemd_service:
    name: clamav-freshclam-once.timer
    enabled: true
    state: started

- name: Set SELinux booleans
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: true
    persistent: true
  loop: "{{ clamav_selinux_bool }}"

- name: Copy mediashuttle clamav config
  ansible.builtin.template:
    src: mediashuttle.conf.j2
    dest: /etc/clamd.d/mediashuttle.conf
    owner: root
    group: root
    mode: "0644"

- name: Enable mediashuttle clamd
  ansible.builtin.systemd_service:
    name: clamd@mediashuttle
    enabled: true
    state: started
