---
- name: Install ClamAV
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ clamav_packages }}"
- name: Enable daily fresh clam signature updates
  ansible.builtin.systemd_service:
    name: clamav-freshclam-once.timer
    enabled: true
